title: Dimitris Vamvourellis
logo: /img/dv_circle.png
description: Masters Student in Data Science, Harvard University
show_downloads: false
google_analytics:
theme: jekyll-theme-minimal

social-network-links:
  # rss: false
  email: "dimvamvourellis@gmail.com"
  github: dvamvourellis
#  reddit: yourname
  linkedin: dimitrisvamvourellis

